title: 'Game Air Hockey '
description: 'Air Hockey game '
template:
  repo: game-air-hockey-template
  name: game-air-hockey
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
